### ISSUE TITLE
Wrong title in Apply Respring alert

### ISSUE THREAD

**Issue by edmechem** [iCrazeiOS/NoTodayView13#1]
![918415AF-4031-4544-9FEB-43DEB0B8EC04](https://user-images.githubusercontent.com/171138/87230004-9529a580-c361-11ea-9d69-77558e67b9fd.jpeg)
It says "SleepSaver" where it should say "NoTodayView13"

**Comment by iCrazeiOS** [comment]
I’ll fix it tonight, thanks for letting me know :)

Probably should’ve checked it a bit more after copy/pasting it from my other tweak 😅

**Comment by iCrazeiOS** [comment]
Pushed a fix to Packix
